from weasyprint import HTML
from jinja2 import Template

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .section { margin-top: 20px; }
        .label { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 50px; font-size: 0.8em; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Biomedical Equipment Inspection Report</h1>
    </div>
    
    <div class="section">
        <h3>Device Information</h3>
        <p><span class="label">Device Name:</span> {{ record.device_name }}</p>
        <p><span class="label">Model:</span> {{ record.model_number }}</p>
        <p><span class="label">Department:</span> {{ record.department }}</p>
    </div>

    <div class="section">
        <h3>Inspection Details</h3>
        <p><span class="label">Date:</span> {{ record.date }}</p>
        <p><span class="label">Inspected By:</span> {{ record.inspected_by }}</p>
    </div>

    <div class="section">
        <h3>Checklist Results</h3>
        <table>
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for item, status in checklist.items() %}
                <tr>
                    <td>{{ item }}</td>
                    <td>{{ status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="section">
        <h3>Remarks</h3>
        <p>{{ record.remarks }}</p>
    </div>

    <div class="footer">
        Generated by Biomedical Equipment Inspection System
    </div>
</body>
</html>
"""

def generate_pdf(record, checklist):
    template = Template(HTML_TEMPLATE)
    html_out = template.render(record=record, checklist=checklist)
    pdf = HTML(string=html_out).write_pdf()
    return pdf
